providers = ["node"]

[variables]
NODE_ENV = "production"

[phases.install]
cmds = [
  "cd app && npm install --legacy-peer-deps",
  "cd backend && npm install --legacy-peer-deps"
]

[phases.build]
cmds = [
  "cd app && npm run build"
]

[start]
cmd = "cd backend && exec node server.js"
